#!/bin/sh

set -e 

if [ ! -d pkg ]; then
    echo "No directory pkg"
    exit -1
fi

version=$(r -e'cat(as.character(read.dcf("pkg/DESCRIPTION")[,"Version"]))')
echo "Working on version $version"

R CMD build --force pkg

test -d ~/www/code/rinside && cp -vax RInside_${version}.tar.gz ~/www/code/rinside


