#!/bin/sh

set -e

if [ ! -d src ]; then
    echo "Not above src/"
    exit -1
fi

cwd=$(pwd)

version=$(r -e'cat(as.character(read.dcf("DESCRIPTION")[,"Version"]))')
echo "Working on version $version"


if [ -x /usr/bin/doxygen ]; then
    cd inst/doc
    rm -rf html/ latex/ man/
    cd ${cwd}
    cd src && ln -s ../inst/examples . && cd -

    ## see FAQ 17 for doxygen
    ( cat doxyfile ; echo PROJECT_NAME="\"RInside Version ${version}\"" ) | doxygen -

    rm src/examples
    cd ${cwd}
    pwd

fi